version: '3.8'

services:
  builder:
    build:
      context: .          # Specifies the build context (current directory)
      dockerfile: builder.Dockerfile  # Dockerfile used to build this service
    container_name: app_builder  # Custom name for the container
    volumes:
      - ./war:/war


  tomcat:
    build:
      context: .          # Specifies the build context (current directory)
      dockerfile: tomcat.Dockerfile # Dockerfile used to build this service
    container_name: app_tomcat
    depends_on:
      - builder  # Ensures that the builder service runs before Tomcat
    ports:
      - "8081:8080"  # Maps port 8081 on the host to port 8080 in the container
    volumes:
      - ./war:/war
    entrypoint: >
      sh -c "while [ ! -f /usr/local/tomcat/webapps/java-tomcat-maven-example.war ]; do
               echo 'Waiting for WAR file...';
               sleep 2;
             done;
             catalina.sh run"
